# Generated by Django 5.2.13 on 2026-04-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contact_details',
            field=models.TextField(blank=True, verbose_name='Kontaktdaten'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ansprechpartner'),
        ),
    ]
