# Generated by Django 5.2.13 on 2026-04-08 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_contact_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_end_date', models.DateField(verbose_name='Altes Vertragsende')),
                ('new_end_date', models.DateField(verbose_name='Neues Vertragsende')),
                ('renewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Verlängert am')),
                ('notes', models.TextField(blank=True, verbose_name='Notiz')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='contracts.contract', verbose_name='Vertrag')),
                ('renewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_renewals', to=settings.AUTH_USER_MODEL, verbose_name='Verlängert von')),
            ],
            options={
                'verbose_name': 'Vertragsverlängerung',
                'verbose_name_plural': 'Vertragsverlängerungen',
                'ordering': ['-renewed_at'],
            },
        ),
    ]
