# Generated by Django 5.2.13 on 2026-04-08 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0004_asset_extended_fields_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seriennummer')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Hersteller')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Standort')),
                ('calibration_interval_days', models.PositiveIntegerField(help_text='z.B. 365 für jährlich, 730 für zweijährlich', verbose_name='Kalibrierintervall (Tage)')),
                ('tolerance', models.CharField(blank=True, help_text='z.B. ±0,1°C oder ±0,5%', max_length=255, verbose_name='Toleranz')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert am')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_equipment', to='assets.asset', verbose_name='Zugehörige Anlage')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_equipment', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlicher')),
            ],
            options={
                'verbose_name': 'Prüfmittel',
                'verbose_name_plural': 'Prüfmittel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_at', models.DateField(blank=True, null=True, verbose_name='Kalibriert am')),
                ('result', models.CharField(blank=True, choices=[('pass', 'Bestanden'), ('fail', 'Nicht bestanden'), ('conditional', 'Bedingt bestanden')], max_length=20, verbose_name='Ergebnis')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifikatsnummer')),
                ('next_due_override', models.DateField(blank=True, help_text='Überschreibt die automatische Berechnung aus dem Intervall', null=True, verbose_name='Nächste Fälligkeit (manuell)')),
                ('external_lab', models.CharField(blank=True, max_length=255, verbose_name='Externes Labor')),
                ('sent_at', models.DateField(blank=True, null=True, verbose_name='Eingesendet am')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Zurückerhalten am')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erfasst am')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Durchgeführt von')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='calibration.testequipment', verbose_name='Prüfmittel')),
            ],
            options={
                'verbose_name': 'Kalibrierungsdurchführung',
                'verbose_name_plural': 'Kalibrierungsdurchführungen',
                'ordering': ['-calibrated_at', '-sent_at', '-created_at'],
            },
        ),
    ]
