# Generated by Django 5.2.12 on 2026-04-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='mainty', max_length=100, verbose_name='Firmenname')),
                ('site_url', models.URLField(default='http://localhost:8000', verbose_name='Site-URL')),
                ('contract_expiry_warning_days', models.PositiveIntegerField(default=90, verbose_name='Vertragswarnung (Tage)')),
                ('reminder_email_subject', models.CharField(default='[mainty] GMP-Erinnerung — Handlungsbedarf', max_length=200, verbose_name='E-Mail-Betreff (Erinnerung)')),
                ('email_from', models.EmailField(default='mainty@localhost', max_length=254, verbose_name='Absender-Adresse')),
                ('email_host', models.CharField(default='localhost', max_length=200, verbose_name='SMTP-Host')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='SMTP-Port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='TLS verwenden')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP-Benutzer')),
                ('email_host_password', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP-Passwort')),
            ],
            options={
                'verbose_name': 'Site-Konfiguration',
            },
        ),
    ]
