# Generated by Django 5.2.13 on 2026-04-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_siteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfig',
            options={'verbose_name': 'Site-Konfiguration', 'verbose_name_plural': 'Site-Konfiguration'},
        ),
    ]
