# Generated by Django 5.2.12 on 2026-04-06 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.CharField(choices=[('herstellung', 'Herstellung'), ('qualitaetskontrolle', 'Qualitätskontrolle'), ('prozessentwicklung', 'Prozessentwicklung')], db_index=True, default='herstellung', max_length=30, verbose_name='Zugehörigkeit'),
        ),
        migrations.AddField(
            model_name='asset',
            name='deputy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_assets', to=settings.AUTH_USER_MODEL, verbose_name='Stellvertreter'),
        ),
        migrations.AddField(
            model_name='asset',
            name='device_code',
            field=models.CharField(default='', max_length=50, verbose_name='Gerätekürzel'),
        ),
        migrations.AddField(
            model_name='asset',
            name='inventory_number',
            field=models.CharField(default='', max_length=100, verbose_name='Inventarnummer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assets', to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlicher'),
        ),
        migrations.AddField(
            model_name='asset',
            name='service_provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='Servicedienstleister'),
        ),
    ]
