# Generated by Django 5.2.12 on 2026-04-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='device_code',
            field=models.CharField(max_length=50, verbose_name='Gerätekürzel'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='inventory_number',
            field=models.CharField(max_length=100, verbose_name='Inventarnummer'),
        ),
    ]
