# Generated by Django 5.2.12 on 2026-04-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_remove_device_code_inventory_number_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='computer_backups_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Backup-Beschreibung'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_backups_enabled',
            field=models.BooleanField(default=False, verbose_name='Backups eingerichtet'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_ip',
            field=models.CharField(blank=True, max_length=50, verbose_name='IP-Adresse'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Computername'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_network_port',
            field=models.CharField(blank=True, max_length=100, verbose_name='Netzwerkdose'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_software_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Software-Version'),
        ),
        migrations.AddField(
            model_name='asset',
            name='computer_windows_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Windows-Version'),
        ),
        migrations.AddField(
            model_name='asset',
            name='has_computer',
            field=models.BooleanField(default=False, verbose_name='Hat zugehörigen Computer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='lock_reason',
            field=models.CharField(blank=True, max_length=500, verbose_name='Sperrgrund'),
        ),
        migrations.AddField(
            model_name='asset',
            name='log_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logbuch (LOG)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='manual_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bedienungsanleitung (BAL)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='Eigentümer'),
        ),
    ]
