# Generated by Django 5.2.12 on 2026-04-04 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeitstempel')),
                ('actor_username', models.CharField(blank=True, max_length=150, verbose_name='Benutzername')),
                ('action', models.CharField(choices=[('CREATE', 'Erstellt'), ('UPDATE', 'Geändert'), ('DELETE', 'Gelöscht'), ('LOGIN', 'Angemeldet'), ('LOGOUT', 'Abgemeldet'), ('LOGIN_FAILED', 'Anmeldung fehlgeschlagen')], db_index=True, max_length=20, verbose_name='Aktion')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='Objekt-ID')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objekt')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Änderungen')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Objekttyp')),
            ],
            options={
                'verbose_name': 'Audit-Eintrag',
                'verbose_name_plural': 'Audit-Trail',
                'ordering': ['-timestamp'],
            },
        ),
    ]
