# Generated by Django 5.2.12 on 2026-04-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('maintenance_overdue', 'Wartung überfällig'), ('maintenance_due_soon', 'Wartung fällig bald'), ('qualification_overdue', 'Qualifizierung überfällig'), ('qualification_due_soon', 'Qualifizierung fällig bald'), ('qualification_never_signed', 'Qualifizierung nie signiert'), ('contract_expiring', 'Vertrag läuft aus'), ('contract_expired', 'Vertrag abgelaufen'), ('task_overdue', 'Aufgabe überfällig')], max_length=40, verbose_name='Kategorie')),
                ('object_id', models.PositiveIntegerField(verbose_name='Objekt-ID')),
                ('message', models.CharField(max_length=255, verbose_name='Meldung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'object_id'), name='unique_notification_per_user_category_object')],
            },
        ),
    ]
