# Generated by Django 5.2.13 on 2026-04-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('maintenance_overdue', 'Wartung überfällig'), ('maintenance_due_soon', 'Wartung fällig bald'), ('qualification_overdue', 'Qualifizierung überfällig'), ('qualification_due_soon', 'Qualifizierung fällig bald'), ('qualification_never_signed', 'Qualifizierung nie signiert'), ('contract_expiring', 'Vertrag läuft aus'), ('contract_expired', 'Vertrag abgelaufen'), ('task_overdue', 'Aufgabe überfällig'), ('calibration_overdue', 'Kalibrierung überfällig'), ('calibration_due_soon', 'Kalibrierung bald fällig')], max_length=40, verbose_name='Kategorie'),
        ),
    ]
